/**
 * Generated bytecode from src/components/vm/bc005.bcs
 */


t_bytecode *generate_dummy_bytecode_bc005_bcs_main(void);
/**
 *
 */
t_bytecode *generate_dummy_bytecode_bc005_bcs_main(void) {
    char byte_code[] = 
        "\x81\x00\x00"         // LOAD_CONST		"io"
        "\x81\x01\x00"         // LOAD_CONST		"::_sfl::io"
        "\x7F"                 // IMPORT
        "\x80\x00\x00"         // STORE_ID		io
        "\x81\x02\x00"         // LOAD_CONST		5
        "\x80\x01\x00"         // STORE_ID		a
        "\x81\x03\x00"         // LOAD_CONST		"True :)"
        "\x80\x02\x00"         // STORE_ID		b
        "\x90\x91\x00"         // SETUP_LOOP		#end_while_001
    // #while_001:
        "\x82\x01\x00"         // LOAD_ID			a
        "\x81\x04\x00"         // LOAD_CONST		20
        "\x95\x03\x00"         // COMPARE_OP		OP_LT
        "\x85\x84\x00"         // JUMP_IF_FALSE	#end_while_001_pb
        "\x01"                 // POP_TOP
    // #if_002:
        "\x82\x01\x00"         // LOAD_ID			a
        "\x81\x05\x00"         // LOAD_CONST		10
        "\x95\x03\x00"         // COMPARE_OP		OP_LT
        "\x85\x1C\x00"         // JUMP_IF_FALSE	#else_if_002
        "\x01"                 // POP_TOP
        "\x81\x06\x00"         // LOAD_CONST		"A LT 10"
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
        "\x82\x01\x00"         // LOAD_ID			a
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
        "\x86\x90\x00"         // JUMP_ABSOLUTE	#end_of_002
    // #else_if_002:
        "\x01"                 // POP_TOP
        "\x81\x08\x00"         // LOAD_CONST		"A GE 10"
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
        "\x82\x01\x00"         // LOAD_ID			a
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
    // #if_003:
        "\x82\x01\x00"         // LOAD_ID			a
        "\x81\x02\x00"         // LOAD_CONST		5
        "\x95\x01\x00"         // COMPARE_OP		OP_EQ
        "\x85\x10\x00"         // JUMP_IF_FALSE	#else_if_003
        "\x01"                 // POP_TOP
        "\x82\x02\x00"         // LOAD_ID			b
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
        "\x86\x90\x00"         // JUMP_ABSOLUTE	#end_of_003
    // #else_if_003:
        "\x01"                 // POP_TOP
        "\x81\x09\x00"         // LOAD_CONST		"False :("
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
    // #end_of_003:
        "\x82\x01\x00"         // LOAD_ID			a
        "\x82\x00\x00"         // LOAD_ID			io
        "\xC0\x07\x00\x01\x00" // CALL_METHOD		"print", $1
        "\x01"                 // POP_TOP
        "\x82\x01\x00"         // LOAD_ID			a
        "\x81\x0A\x00"         // LOAD_CONST		1
        "\x17"                 // BINARY_ADD
        "\x80\x01\x00"         // STORE_ID		a
        "\x86\x19\x00"         // JUMP_ABSOLUTE	#while_001
    // #end_while_001_pb:
        "\x72"                 // POP_BLOCK
    ;
    t_bytecode *bc = (t_bytecode *)smm_malloc(sizeof(t_bytecode));
    bzero(bc, sizeof(t_bytecode));
    bc->stack_size = 25;
    bc->code_len = sizeof(byte_code);
    bc->code = smm_malloc(bc->code_len);
    memcpy(bc->code, byte_code, bc->code_len);

    bc->constants = NULL;   // Important to start constants and identifiers on NULL
    bc->identifiers = NULL;

    // constants
    _new_constant_string(bc, "io");
    _new_constant_string(bc, "::_sfl::io");
    _new_constant_long(bc, 5);
    _new_constant_string(bc, "True :)");
    _new_constant_long(bc, 20);
    _new_constant_long(bc, 10);
    _new_constant_string(bc, "A LT 10");
    _new_constant_string(bc, "print");
    _new_constant_string(bc, "A GE 10");
    _new_constant_string(bc, "False :(");
    _new_constant_long(bc, 1);

    // identifier names
    _new_name(bc, "io");
    _new_name(bc, "a");
    _new_name(bc, "b");
    _new_name(bc, "OP_LT");
    
    return bc;
}




