<?php

/*
 * This script creates a _exceptions.c and .h file from our exceptions.dat template.
 */

$exception_stack = array();
$cur_level = -1;

// Read exception
$exceptions = array();
foreach (file($argv[1]) as $line) {
    // Skip empty en comments lines
    $tmp = trim($line);
    if (empty($tmp)) continue;
    if ($tmp[0] == '#') continue;

    $new_level = 0;
    while ($line[$new_level] == ' ') $new_level++;
    $new_level /= 4;        // indentation is 4 spaces!

    $line = trim($line);

    if ($new_level == $cur_level) {
        array_pop($exception_stack);
    } elseif ($new_level < $cur_level) {
        // Pop items until we hit the needed level
        while (count($exception_stack) > $new_level) {
            array_pop($exception_stack);
        }
    }

    $parent = count($exception_stack) > 0 ? $exception_stack[count($exception_stack)-1] : "";
    $exceptions[] = array(ucfirst($line), ucfirst($parent));

    array_push($exception_stack, $line);
    $cur_level = $new_level;
}


/*
 * Write H file
 */

$fp = fopen($argv[2], "w");

$header = <<< EOH
/*
 Copyright (c) 2012-2013, The Saffire Group
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Saffire Group the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#ifndef ___EXCEPTIONS_H__
#define ___EXCEPTIONS_H__


    /*
     * WARNING: THIS FILE IS AUTOGENERATED! PLEASE USE CREATE_EXCEPTIONS.PHP TO REGENERATE!
     */


EOH;
fwrite($fp, $header);

foreach ($exceptions as $exception) {
    list($exception, $parent) = $exception;

    fwrite($fp, "    // {$exception}\n");
    fwrite($fp, "    t_exception_object Object_Exception_{$exception}_struct;\n");
    fwrite($fp, "    #define Object_{$exception} ((t_object *)&Object_Exception_{$exception}_struct)\n");
    fwrite($fp, "\n");
}

$footer = <<< EOT
#endif
EOT;
fwrite($fp, $footer);

fclose($fp);





// Write C file
$fp = fopen($argv[3], "w");

$header = <<< EOH
/*
 Copyright (c) 2012-2013, The Saffire Group
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the Saffire Group the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

    /*
     * WARNING: THIS FILE IS AUTOGENERATED! PLEASE USE CREATE_EXCEPTIONS.PHP TO REGENERATE!
     */

EOH;
fwrite($fp, $header);


fwrite($fp, "void object_exception_add_generated_exceptions(void) {\n");
foreach ($exceptions as $exception) {
    list($exception, $parent) = $exception;

    fwrite($fp, "    //${exception}\n");
    fwrite($fp, "    Object_Exception_${exception}_struct.attributes = Object_Exception_struct.attributes;\n");
    fwrite($fp, "    vm_populate_builtins(\"".lcfirst($exception)."\", Object_${exception});\n");
    fwrite($fp, "    \n");
}
fwrite($fp, "}\n");

fwrite($fp, "\n\n");


foreach ($exceptions as $exception) {
    list($exception, $parent) = $exception;

    fwrite($fp, "t_exception_object Object_Exception_{$exception}_struct = { OBJECT_HEAD_INIT_WITH_BASECLASS(\"".lcfirst($exception)."\", objectTypeException, OBJECT_TYPE_INSTANCE | OBJECT_FLAG_STATIC | OBJECT_FLAG_IMMUTABLE, &exception_funcs, (t_object *)&Object_Exception_".(empty($parent)?"":$parent."_")."struct), \"\", 0};\n");
}

fclose($fp);
