#line 2 "compiler/lex.yy.c"

#line 4 "compiler/lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 69
#define YY_END_OF_BUFFER 70
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[260] =
    {   0,
        0,    0,    0,    0,    0,    0,   70,   68,    2,    2,
        4,   68,   66,    4,   68,   68,    4,    4,    4,    4,
        4,   67,    4,    4,    4,    4,   66,    4,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   68,   68,    4,    3,    2,   10,    0,
       64,   66,   20,   13,   21,    0,   65,   18,   26,   16,
       27,   17,    0,    0,   19,   67,    0,   14,    8,    9,
        7,   15,   66,   66,   23,   66,   32,   66,   66,   66,
       66,   66,   33,   66,   66,   66,   66,   66,   29,   66,
       11,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   66,   66,   22,   12,    6,    0,    0,    5,   19,
        0,    0,    0,    1,   66,   24,   25,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   34,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   58,   31,   66,    5,    0,    0,    5,    0,
        1,    0,    1,   66,   66,   61,   66,   66,   66,   66,
       66,   30,   66,   66,   66,   60,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   62,   66,   66,   66,
       66,    5,    1,    5,    0,    0,    0,   66,   55,   51,
       37,   43,   66,   66,   66,   41,   66,   66,   66,   66,

       66,   66,   66,   66,   66,   66,   66,   66,   66,   53,
       28,    0,    0,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   48,   63,   66,   66,   66,   45,   66,   54,
       44,   36,   66,   66,   66,   59,   38,   52,   35,   66,
       66,   46,   66,   66,   66,   40,   66,   57,   66,   66,
       50,   66,   49,   56,   66,   42,   47,   39,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    6,    7,    8,    9,   10,
       10,   11,   12,   10,   13,   10,   14,   15,   15,   15,
       15,   15,   15,   15,   15,   15,   15,   16,   10,   17,
       18,   19,   20,    1,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       10,   22,   10,   23,   21,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   33,   40,   41,   42,   43,   44,   45,   46,
       47,   33,   10,   48,   10,   49,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,

       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21,   21,   21,   21,   21,   21,
       21,   21,   21,   21,   21
    } ;

static yyconst flex_int32_t yy_meta[50] =
    {   0,
        1,    1,    2,    3,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    4,    1,    1,    1,    1,    3,
        4,    1,    1,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    1,    1
    } ;

static yyconst flex_int16_t yy_base[273] =
    {   0,
        0,    0,  323,  294,  293,  287,  265,  804,   48,   50,
      245,  256,    0,  210,   46,  207,  804,  185,   43,   44,
       45,  186,  172,   48,  166,   49,   54,  152,   56,   65,
       66,   68,   67,   71,   69,   79,   90,  107,   94,  113,
      108,   80,  115,   75,  148,  118,  131,   75,  804,  160,
      804,    0,  804,  804,  804,  147,  804,  804,  804,  804,
      804,  804,  140,    0,  804,  115,  113,  106,  804,  804,
      804,  102,  804,   75,  804,  133,  134,  139,  140,  148,
      153,  157,  158,  159,  160,  167,  165,  171,  172,  179,
      189,  190,  194,  191,  192,  202,  204,  216,  215,  217,

      221,  223,  226,  804,  804,  804,  112,  231,  245,  175,
        0,   81,   68,    0,  804,  804,  804,  289,  290,  234,
      229,  291,  292,  293,  295,  296,  298,  299,  300,  301,
      321,  322,  324,  325,  326,  331,  335,  336,  343,  339,
      344,  350,  244,  246,  354,    0,  245,  193,  389,  249,
        0,  284,  804,  435,  353,  356,  436,  437,  438,  439,
      440,  357,  442,  441,  444,  363,  445,  446,  443,  450,
      465,  468,  470,  473,  480,  487,  488,  490,  491,  493,
      495,    0,    0,    0,  490,  492,  502,  505,  515,  516,
      517,  522,  524,  527,  526,  528,  529,  530,  536,  537,

      547,  548,  554,  550,  555,  565,  567,  573,  575,  568,
      576,  586,  564,  587,  594,  597,  599,  601,  605,  606,
      607,  608,  611,  614,  616,  618,  619,  626,  629,  639,
      643,  646,  647,  649,  650,  651,  652,  653,  654,  661,
      671,  664,  672,  673,  675,  676,  679,  682,  683,  684,
      690,  696,  701,  704,  707,  709,  710,  711,  804,  748,
      750,  755,  758,  763,  768,  773,  778,  783,   75,  788,
      793,  798
    } ;

static yyconst flex_int16_t yy_def[273] =
    {   0,
      259,    1,    1,    1,    1,    1,  259,  259,  259,  259,
      259,  260,  261,  259,  259,  262,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  263,  259,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  259,  259,  264,  259,  259,  259,  260,
      259,  261,  259,  259,  259,  262,  259,  259,  259,  259,
      259,  259,  265,  266,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  263,  259,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  259,  259,  259,  264,  267,  266,  264,
      268,  265,  265,  266,  259,  259,  259,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  269,  267,  267,  259,  270,
      109,  271,  259,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  269,  269,  149,  272,  272,  271,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  272,  272,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,    0,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259
    } ;

static yyconst flex_int16_t yy_nxt[854] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   17,
       27,    8,   28,   29,   30,   31,   32,   33,   34,   35,
       27,   36,   27,   27,   27,   37,   27,   27,   38,   39,
       40,   41,   42,   27,   43,   27,   27,   44,   45,   48,
       48,   48,   48,   54,   59,   63,   61,   73,   64,   73,
       60,   62,   65,   55,   68,   69,   71,   72,   73,   73,
       73,   73,   73,   73,   73,   73,   48,   48,   73,  182,
       76,  153,   73,   73,   73,   73,   73,   73,   73,   79,
       73,  113,  104,   73,   73,   82,   77,   73,   73,   73,

       80,   84,   86,   81,   78,   83,   88,   89,   87,   73,
       73,   73,   85,   73,   90,   91,   73,   92,   73,  117,
      102,   96,  105,  116,  115,  146,   73,   73,  108,   66,
       93,  109,   73,  111,   73,  110,   73,   73,  100,  111,
       97,   63,   73,   73,   64,  103,   94,  101,   65,   95,
      113,   73,   73,   73,   98,   57,   73,   99,   73,   73,
       73,   73,   73,   73,   51,  106,  119,   73,   73,   75,
       73,  122,   73,  118,   73,   73,   73,   73,   73,   73,
      120,  121,   73,   70,   73,  124,   73,   67,  146,  123,
       73,   73,   73,   73,   73,   73,  111,   73,   73,  125,

       66,  126,   58,  127,  128,   73,  183,   73,   73,   73,
       73,   73,  129,   73,  150,   57,  136,  130,   73,   73,
       73,   73,  134,   73,   73,  137,   73,   53,  135,   73,
      131,  132,   73,  133,   73,   73,   73,   73,  139,  140,
       73,  148,   73,  138,  149,   73,  141,   73,   73,   73,
      144,  112,  150,   73,  157,  148,  142,  145,  149,  186,
       51,  156,   49,   73,  259,   73,  150,  143,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,  151,  151,  151,  151,  151,  151,  151,  151,
      151,  151,   73,   73,   73,   73,   73,  146,   73,   73,

       47,   73,   73,   73,   73,  111,   47,   46,   73,   73,
       73,   73,   73,  155,   73,   73,  161,   73,   73,   73,
       73,  164,  162,  163,   73,   73,  165,   73,   73,   73,
      154,  158,  159,  160,   73,  167,   46,  166,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,  168,  259,
       73,  170,  169,   73,   73,   73,   73,   73,   73,   73,
       73,  175,   73,   73,  172,  174,   73,  173,  171,   73,
      259,  177,   73,   73,  259,   73,   73,  259,  176,  259,
      178,  259,   73,  259,  259,  179,  189,  180,  181,  112,
      112,  112,  112,  112,  112,  112,  112,  112,  112,  113,

      112,  112,  112,  112,  112,  112,  112,  112,  112,  112,
      112,  112,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  184,  184,  184,  184,
      184,  184,  184,  184,  184,  184,  112,  112,   73,   73,
       73,   73,   73,   73,   73,   73,   73,   73,   73,   73,
      259,  259,  259,   73,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,  190,  197,   73,   73,
      193,   73,  198,   73,  188,  196,   73,  191,  195,  192,
      200,  259,  194,   73,   73,  199,  201,   73,  202,   73,
       73,   73,   73,   73,   73,  203,   73,  204,   73,   73,

      213,  259,  259,  149,  205,  183,   73,   73,   73,   73,
       73,  150,   73,  150,   73,  146,  209,  206,   73,   73,
       73,  208,  211,  111,   73,   73,  207,   73,  214,   73,
       73,   73,   73,   73,   73,   73,   73,  210,  259,   73,
       73,   73,  215,   73,  259,   73,   73,   73,   73,   73,
       73,   73,  218,   73,  220,   73,   73,   73,   73,  259,
      216,  217,  219,  223,  222,  221,   73,   73,   73,   73,
       73,   73,  259,   73,   73,  227,   73,  183,   73,   73,
      228,  259,  259,  259,   73,  150,   73,   73,  224,  225,
       73,  259,   73,  226,   73,   73,  213,   73,  231,  149,

       73,  229,   73,  230,   73,  232,   73,  150,   73,   73,
       73,   73,  233,   73,   73,  259,   73,   73,   73,   73,
       73,   73,   73,  259,   73,   73,   73,   73,  234,   73,
       73,  241,   73,   73,  240,   73,  239,   73,   73,  235,
      236,  237,   73,  242,  259,   73,   73,  259,   73,   73,
       73,  238,   73,   73,   73,   73,   73,   73,   73,  243,
      244,  259,   73,  245,   73,   73,   73,   73,   73,   73,
       73,   73,   73,   73,   73,   73,   73,  248,   73,   73,
       73,  259,   73,   73,  259,   73,   73,   73,  246,  247,
       73,   73,   73,   73,   73,   73,  250,  249,   73,   73,

      252,   73,   73,   73,   73,  259,  254,   73,  259,   73,
       73,  256,   73,   73,   73,   73,  259,  259,  251,  259,
       73,  253,  257,   73,  255,  259,   73,  259,   73,   73,
       73,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  258,   50,   50,
       50,   50,   50,   52,   52,   56,   56,   56,   56,   56,
       74,   74,   74,  107,  107,  107,  107,  107,  112,  112,
      112,  112,  112,  114,  259,  114,  114,  114,  147,  147,
      147,  147,  147,  152,  259,  152,  152,  152,  185,  185,
      185,  185,  185,  187,  187,  187,  187,  187,  212,  212,

      212,  212,  212,    7,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259
    } ;

static yyconst flex_int16_t yy_chk[854] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    9,
        9,   10,   10,   15,   19,   21,   20,   27,   21,   29,
       19,   20,   21,   15,   24,   24,   26,   26,   30,   31,
       33,   32,   35,   27,   34,   29,   48,   48,   74,  269,
       29,  113,   36,   42,   30,   31,   33,   32,   35,   31,
       34,  112,   44,   37,   74,   32,   29,   39,   36,   42,

       31,   33,   34,   31,   30,   32,   35,   36,   34,   37,
       38,   41,   33,   39,   36,   36,   40,   37,   43,   72,
       42,   39,   44,   68,   67,  107,   38,   41,   46,   66,
       38,   46,   40,  107,   43,   46,   76,   77,   41,   46,
       40,   47,   78,   79,   47,   43,   38,   41,   47,   38,
       63,   80,   76,   77,   40,   56,   81,   40,   78,   79,
       82,   83,   84,   85,   50,   45,   78,   80,   87,   28,
       86,   80,   81,   76,   88,   89,   82,   83,   84,   85,
       79,   79,   90,   25,   87,   82,   86,   23,  110,   81,
       88,   89,   91,   92,   94,   95,  110,   93,   90,   84,

       22,   85,   18,   86,   87,   96,  148,   97,   91,   92,
       94,   95,   88,   93,  148,   16,   95,   90,   99,   98,
      100,   96,   94,   97,  101,   96,  102,   14,   94,  103,
       91,   92,  121,   93,   99,   98,  100,  120,   97,   98,
      101,  108,  102,   96,  108,  103,   99,  143,  121,  144,
      102,  150,  108,  120,  121,  147,  100,  103,  147,  150,
       12,  120,   11,  143,    7,  144,  147,  101,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  109,  109,  109,  109,  109,  109,  109,  109,
      109,  109,  118,  119,  122,  123,  124,  152,  125,  126,

        6,  127,  128,  129,  130,  152,    5,    4,  118,  119,
      122,  123,  124,  119,  125,  126,  124,  127,  128,  129,
      130,  127,  125,  126,  131,  132,  128,  133,  134,  135,
      118,  122,  123,  123,  136,  130,    3,  129,  137,  138,
      131,  132,  140,  133,  134,  135,  139,  141,  131,    0,
      136,  133,  132,  142,  137,  138,  155,  145,  140,  156,
      162,  137,  139,  141,  135,  136,  166,  135,  134,  142,
        0,  139,  155,  145,    0,  156,  162,    0,  138,    0,
      140,    0,  166,    0,    0,  141,  155,  142,  145,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,

      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  149,  149,
      149,  149,  149,  149,  149,  149,  149,  149,  154,  157,
      158,  159,  160,  161,  164,  163,  169,  165,  167,  168,
        0,    0,    0,  170,  154,  157,  158,  159,  160,  161,
      164,  163,  169,  165,  167,  168,  157,  165,  171,  170,
      160,  172,  167,  173,  154,  164,  174,  158,  163,  159,
      169,    0,  161,  175,  171,  168,  170,  172,  171,  173,
      176,  177,  174,  178,  179,  172,  180,  173,  181,  175,

      185,    0,    0,  185,  174,  186,  176,  177,  188,  178,
      179,  185,  180,  186,  181,  187,  179,  175,  189,  190,
      191,  178,  181,  187,  188,  192,  176,  193,  188,  195,
      194,  196,  197,  198,  189,  190,  191,  180,    0,  199,
      200,  192,  189,  193,    0,  195,  194,  196,  197,  198,
      201,  202,  195,  204,  197,  199,  200,  203,  205,    0,
      193,  194,  196,  200,  199,  198,  201,  202,  206,  204,
      207,  210,    0,  203,  205,  204,  208,  213,  209,  211,
      205,    0,    0,    0,  206,  213,  207,  210,  201,  202,
      214,    0,  208,  203,  209,  211,  212,  215,  208,  212,

      216,  206,  217,  207,  218,  209,  214,  212,  219,  220,
      221,  222,  214,  215,  223,    0,  216,  224,  217,  225,
      218,  226,  227,    0,  219,  220,  221,  222,  215,  228,
      223,  222,  229,  224,  221,  225,  220,  226,  227,  216,
      217,  218,  230,  225,    0,  228,  231,    0,  229,  232,
      233,  219,  234,  235,  236,  237,  238,  239,  230,  226,
      227,    0,  231,  229,  240,  232,  233,  242,  234,  235,
      236,  237,  238,  239,  241,  243,  244,  235,  245,  246,
      240,    0,  247,  242,    0,  248,  249,  250,  233,  234,
      241,  243,  244,  251,  245,  246,  241,  240,  247,  252,

      244,  248,  249,  250,  253,    0,  247,  254,    0,  251,
      255,  250,  256,  257,  258,  252,    0,    0,  243,    0,
      253,  245,  252,  254,  249,    0,  255,    0,  256,  257,
      258,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,  255,  260,  260,
      260,  260,  260,  261,  261,  262,  262,  262,  262,  262,
      263,  263,  263,  264,  264,  264,  264,  264,  265,  265,
      265,  265,  265,  266,    0,  266,  266,  266,  267,  267,
      267,  267,  267,  268,    0,  268,  268,  268,  270,  270,
      270,  270,  270,  271,  271,  271,  271,  271,  272,  272,

      272,  272,  272,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259,  259,  259,  259,  259,  259,  259,  259,
      259,  259,  259
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[70] =
    {   0,
1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 1, 1, 0, 0, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compiler/saffire.l"
/*
 Copyright (c) 2012, The Saffire Group
 All rights reserved.

 Redistribution and use in source and binary forms, with or without
 modification, are permitted provided that the following conditions are met:
     * Redistributions of source code must retain the above copyright
       notice, this list of conditions and the following disclaimer.
     * Redistributions in binary form must reproduce the above copyright
       notice, this list of conditions and the following disclaimer in the
       documentation and/or other materials provided with the distribution.
     * Neither the name of the <organization> nor the
       names of its contributors may be used to endorse or promote products
       derived from this software without specific prior written permission.

 THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
 ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
 WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 DISCLAIMED. IN NO EVENT SHALL COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY
 DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
 SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/
#line 28 "compiler/saffire.l"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

#include "compiler/ast.h"
#include "compiler/parser.tab.h"

#define YY_NO_INPUT 1
#define YYPRINT 1

    static void yy_push_state (int new_state );
    static void yy_pop_state (void );

void saffire_push_state(int state) {
    yy_push_state(state);
}

void saffire_pop_state() {
    yy_pop_state();
}

/* Exclusive - only match <regex> rules */


/* suppres -Wall warning about yyunput */
#line 808 "compiler/lex.yy.c"

#define INITIAL 0
#define st_regex 1
#define st_div 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state (int new_state );
    
    static void yy_pop_state (void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 68 "compiler/saffire.l"


#line 1006 "compiler/lex.yy.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 260 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 804 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 70 "compiler/saffire.l"
{ }
	YY_BREAK
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 71 "compiler/saffire.l"
{ }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 73 "compiler/saffire.l"
{ return '/'; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 75 "compiler/saffire.l"
{ saffire_push_state(st_regex); return yytext[0]; }
	YY_BREAK
/* Only match regex when we are in the regex state */
case 5:
/* rule 5 can match eol */
YY_RULE_SETUP
#line 79 "compiler/saffire.l"
{ return T_REGEX; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 81 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_RE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 82 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_GE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 83 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_LE; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 84 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_EQ; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 85 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_NE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 86 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_IN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 88 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_OR; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 89 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_AND; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 91 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SHIFT_LEFT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 92 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SHIFT_RIGHT; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 94 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PLUS_ASSIGNMENT; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 95 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_MINUS_ASSIGNMENT; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 96 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_MUL_ASSIGNMENT; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 97 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_DIV_ASSIGNMENT; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 98 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_MOD_ASSIGNMENT; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 99 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_AND_ASSIGNMENT; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 100 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_OR_ASSIGNMENT; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 101 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_XOR_ASSIGNMENT; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 102 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SL_ASSIGNMENT; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 103 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SR_ASSIGNMENT; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 105 "compiler/saffire.l"
{ saffire_push_state(st_div); return T_OP_INC; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 106 "compiler/saffire.l"
{ saffire_push_state(st_div); return T_OP_DEC; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 108 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_WHILE; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 109 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_IF; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 110 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_ELSE; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 111 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_USE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 112 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_AS; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 113 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_DO; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 114 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_FOR; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 115 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_FOREACH; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 116 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SWITCH; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 118 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_CLASS; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 119 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_EXTENDS; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 120 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_IMPLEMENTS; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 121 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_ABSTRACT; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 122 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_FINAL; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 123 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_INTERFACE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 124 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_CONST; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 125 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_STATIC; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 127 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PUBLIC; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 128 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PRIVATE; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 129 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PROTECTED; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 130 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_METHOD; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 131 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_READONLY; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 132 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PROPERTY; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 134 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_CATCH; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 135 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_FINALLY; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 136 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_THROW; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 137 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_RETURN; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 138 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_BREAK; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 139 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_BREAKELSE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 140 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_CONTINUE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 141 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_TRY; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 142 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_DEFAULT; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 143 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_GOTO; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 144 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_CASE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 146 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_SELF; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 147 "compiler/saffire.l"
{ saffire_push_state(st_regex); return T_PARENT; }
	YY_BREAK
case 64:
/* rule 64 can match eol */
YY_RULE_SETUP
#line 150 "compiler/saffire.l"
{
    saffire_push_state(st_div);
    yylval.sVal = strdup(yytext+1);
    if (yylval.sVal[yyleng-2] != yytext[0]) {
        fprintf(stderr,"improperly terminated string");
    } else {
        yylval.sVal[yyleng-2] = 0;
    }
    return T_STRING; }
	YY_BREAK
case 65:
/* rule 65 can match eol */
YY_RULE_SETUP
#line 160 "compiler/saffire.l"
{
    saffire_push_state(st_div);
    yylval.sVal = strdup(yytext+1);
    if (yylval.sVal[yyleng-2] != yytext[0]) {
        fprintf(stderr,"improperly terminated string");
    } else {
        yylval.sVal[yyleng-2] = 0;
    }
    return T_STRING; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 170 "compiler/saffire.l"
{
    saffire_push_state(st_div);
    yylval.sVal = strdup(yytext);
    return T_IDENTIFIER;
}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 176 "compiler/saffire.l"
{
    saffire_push_state(st_div);
    yylval.lVal = strtol(yytext, NULL, 10);
    return T_LNUM; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 181 "compiler/saffire.l"
{
    printf ("Unknown token: '%s'\n", yytext);
    yyterminate();
}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 186 "compiler/saffire.l"
ECHO;
	YY_BREAK
#line 1476 "compiler/lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(st_regex):
case YY_STATE_EOF(st_div):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 260 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 260 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 259);

	return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree((yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 186 "compiler/saffire.l"



int yywrap(void) { return 1; }


