// Warning: this file is autogenerated. Do not modify.
#ifndef __GITVERSION_H__
#define __GITVERSION_H__

   #define __GIT_REVISION__ "@GITREV_SHA1@"
   const char git_revision_str[] = __GIT_REVISION__;

#endif
